package com.qsj.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "ad_id", Admin.class);
		// Composite Primary Key order: ad_id,ad_username
		arp.addMapping("admin_details", "ad_id,ad_username", AdminDetails.class);
		arp.addMapping("admin_transition", "ad_username", AdminTransition.class);
		arp.addMapping("classs", "cls_id", Classs.class);
		arp.addMapping("student", "s_id", Student.class);
		arp.addMapping("subject", "sub_id", Subject.class);
		arp.addMapping("teacher", "t_id", Teacher.class);
	}
}

