package com.qsj.model;

import com.qsj.model.pojo.BaseAdminTransition;

/**
 * Generated by JFinal.
 * @author 84735
 */
@SuppressWarnings("serial")
public class AdminTransition extends BaseAdminTransition<AdminTransition> {
	public static final AdminTransition dao = new AdminTransition();
}
