package com.qsj.model;

import com.qsj.model.pojo.BaseClasss;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classs extends BaseClasss<Classs> {
	public static final Classs dao = new Classs();
	public List<Student> getStudents(Integer page , Integer pageSize , String username){
		return Student.dao.find("select * from student where s_class = ? and s_name like '%' ? '%' limit ? , ? " , get("cls_id") ,username,pageSize*(page-1),pageSize);
	}

	public List<Teacher> getTeachers(Integer t_subject){
		return Teacher.dao.find("select * from teacher where t_subject = ? ",t_subject);
	}

	public Teacher getChineseTeacher(Integer t_subject){
		return Teacher.dao.findById(get("cls_chinese"));
	}
}
