package com.qsj.model;

import com.qsj.model.pojo.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
	public static final Student dao = new Student();
	public Classs getClasss(){
		return Classs.dao.findById(get("cls_id"));
	}
}
