package com.qsj.model;

import com.qsj.model.pojo.BaseSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subject extends BaseSubject<Subject> {
	public static final Subject dao = new Subject();
}
