package com.qsj.model;

import com.qsj.model.pojo.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher();
	public Subject getSubject(){
		return Subject.dao.findById(get("t_subject"));
	}
}
