package com.qsj.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public void setTName(java.lang.String tName) {
		set("t_name", tName);
	}

	public java.lang.String getTName() {
		return get("t_name");
	}

	public void setTGender(java.lang.Integer tGender) {
		set("t_gender", tGender);
	}

	public java.lang.Integer getTGender() {
		return get("t_gender");
	}

	public void setTSubject(java.lang.Integer tSubject) {
		set("t_subject", tSubject);
	}

	public java.lang.Integer getTSubject() {
		return get("t_subject");
	}

}
