package com.qsj.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSubject<M extends BaseSubject<M>> extends Model<M> implements IBean {

	public void setSubId(java.lang.Integer subId) {
		set("sub_id", subId);
	}

	public java.lang.Integer getSubId() {
		return get("sub_id");
	}

	public void setSubDetail(java.lang.String subDetail) {
		set("sub_detail", subDetail);
	}

	public java.lang.String getSubDetail() {
		return get("sub_detail");
	}

}
