package com.qsj.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminDetails<M extends BaseAdminDetails<M>> extends Model<M> implements IBean {

	public void setAdId(java.lang.Integer adId) {
		set("ad_id", adId);
	}

	public java.lang.Integer getAdId() {
		return get("ad_id");
	}

	public void setAdUsername(java.lang.String adUsername) {
		set("ad_username", adUsername);
	}

	public java.lang.String getAdUsername() {
		return get("ad_username");
	}

	public void setAdLogintime(java.util.Date adLogintime) {
		set("ad_logintime", adLogintime);
	}

	public java.util.Date getAdLogintime() {
		return get("ad_logintime");
	}

}
